export const CATEGORIES = ['Employee', 'Student', 'Intern', 'Consultant', 'Trainer', 'Volunteer', 'Research Associate', 'Project Associate', 'HR', 'Management', 'Guest', 'Vendor', 'Visitor', 'Contractor', 'Others'];

export const DEPARTMENTS_BY_CATEGORY = {
  Employee: ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Sales', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration', 'Engineering', 'Product', 'Design', 'Customer Support', 'Legal', 'Procurement', 'Logistics', 'R&D'],
  Student: ['General', 'Computer Science', 'Business', 'Engineering', 'Arts', 'Science'],
  Intern: ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration'],
  Consultant: ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration'],
  Trainer: ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration'],
  Volunteer: ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration'],
  'Research Associate': ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration'],
  'Project Associate': ['General', 'IT', 'Software Development', 'GIS & Remote Sensing', 'Human Resources', 'Finance', 'Marketing', 'Business Development', 'Artificial Intelligence', 'Cyber Security', 'UI/UX Design', 'Operations', 'Administration'],
  HR: ['General', 'Human Resources'],
  Management: ['General', 'Operations', 'Administration', 'Business Development'],
  Guest: ['General', 'Client Visit', 'Meeting'],
  Vendor: ['General', 'IT Services', 'Facility Management', 'Catering', 'Security', 'Transport', 'Maintenance', 'Supply Chain', 'Printing & Stationery', 'Cleaning Services', 'Electrical'],
  Visitor: ['General', 'Client Visit', 'Government', 'Audit', 'Interview', 'Meeting', 'Event', 'Delivery'],
  Contractor: ['General', 'IT', 'Civil', 'Electrical', 'Mechanical', 'Construction', 'Plumbing', 'HVAC', 'Interior Design', 'Landscaping', 'Security Systems'],
  Others: ['General', 'Temporary Staff', 'Freelancer', 'Partner', 'Board Member', 'Advisor', 'Volunteer']
};

export const DESIGNATIONS_MAPPING = {
  Employee: {
    IT: ['Software Engineer', 'Senior Software Engineer', 'Lead Engineer', 'Tech Lead', 'System Admin', 'DevOps Engineer', 'Database Administrator', 'IT Support Specialist', 'Network Engineer', 'Security Analyst', 'Architect', 'Systems Architect', 'Solutions Architect', 'Cloud Architect', 'Infrastructure Engineer', 'Site Reliability Engineer', 'IT Manager', 'CTO', 'Technical Lead'],
    'Human Resources': ['HR Manager', 'HR Executive', 'Recruiter', 'Talent Acquisition Specialist', 'HR Operations', 'Senior HR Manager', 'Compensation & Benefits', 'Employee Relations Manager', 'HR Generalist', 'HR Analyst', 'CHRO', 'People Operations Manager', 'Culture Head'],
    General: ['Employee', 'Staff Member', 'Office Assistant', 'Support Staff', 'Security Guard', 'Driver', 'Office Boy', 'Peon', 'Office Manager', 'Receptionist', 'Helper'],
    'Software Development': ['Full Stack Developer', 'Frontend Developer', 'Backend Developer', 'Lead Developer', 'Technical Architect', 'Software Engineer', 'QA Engineer', 'DevOps Engineer', 'Mobile App Developer', 'Android Developer', 'iOS Developer', 'React Developer', 'Node.js Developer', 'Python Developer', 'Java Developer', 'PHP Developer', 'Software Architect', 'Engineering Manager'],
    'GIS & Remote Sensing': ['GIS Analyst', 'GIS Developer', 'Remote Sensing Specialist', 'GIS Specialist', 'Photogrammetrist', 'Surveyor', 'Cartographer', 'GIS Manager', 'Geospatial Engineer', 'LiDAR Specialist', 'Image Processing Expert', 'GIS Consultant'],
    Finance: ['Accountant', 'Financial Analyst', 'Finance Manager', 'Billing Executive', 'Internal Auditor', 'Tax Consultant', 'CFO', 'Accounts Manager', 'Accounts Executive', 'Investment Analyst', 'Budget Analyst', 'Audit Manager'],
    Marketing: ['Marketing Manager', 'Digital Marketing Executive', 'Content Strategist', 'SEO Specialist', 'Social Media Manager', 'Marketing Coordinator', 'Brand Manager', 'Public Relations Manager', 'Content Creator', 'Email Marketer', 'Growth Hacker', 'CMO', 'Marketing Director'],
    Sales: ['Sales Manager', 'Business Development Executive', 'Account Manager', 'Sales Coordinator', 'Area Sales Manager', 'Sales Executive', 'Relationship Manager', 'Territory Manager', 'Sales Director', 'VP Sales'],
    'Business Development': ['BD Manager', 'Strategic Partnership Manager', 'Market Researcher', 'Lead Generation Specialist', 'Growth Manager', 'Alliance Manager', 'BD Executive'],
    'Artificial Intelligence': ['AI Engineer', 'Machine Learning Engineer', 'Data Scientist', 'AI Researcher', 'AI Analyst', 'NLP Engineer', 'Computer Vision Engineer', 'Big Data Architect', 'Data Engineer', 'AI Consultant'],
    'Cyber Security': ['Cyber Security Analyst', 'Ethical Hacker', 'Security Engineer', 'Security Consultant', 'Compliance Officer', 'CISO', 'Security Architect', 'Network Security Engineer', 'Forensics Expert'],
    'UI/UX Design': ['UI/UX Designer', 'Product Designer', 'Interaction Designer', 'Visual Designer', 'UX Researcher', 'Design Manager', 'Experience Lead', 'Creative Director'],
    Operations: ['Operations Manager', 'Operations Coordinator', 'Logistics Coordinator', 'Supply Chain Analyst', 'Manager', 'Senior Manager', 'VP Operations', 'Director', 'COO', 'General Manager', 'Assistant Manager'],
    Administration: ['Admin Manager', 'Admin Executive', 'Facility Manager', 'Office Coordinator', 'Executive', 'Administrator', 'Office Admin', 'Admin Lead'],
    Engineering: ['Mechanical Engineer', 'Electrical Engineer', 'Civil Engineer', 'Project Engineer', 'Draftsman', 'Safety Engineer', 'Structural Engineer', 'Site Engineer', 'Estimator'],
    Product: ['Product Manager', 'Associate Product Manager', 'Product Analyst', 'Product Designer', 'Technical Product Manager', 'Product Owner', 'Head of Product'],
    Design: ['Graphic Designer', 'UI/UX Designer', 'Visual Designer', 'Art Director', 'Brand Designer', 'Illustrator', 'Motion Graphics Designer'],
    'Customer Support': ['Support Lead', 'Customer Success Manager', 'Support Executive', 'Help Desk Technician', 'Customer Care Manager', 'Client Support Specialist'],
    Legal: ['Legal Counsel', 'Legal Advisor', 'Legal Assistant', 'Compliance Officer', 'Company Secretary', 'Attorney', 'Paralegal', 'Legal Manager'],
    Procurement: ['Procurement Manager', 'Purchase Executive', 'Vendor Manager', 'Sourcing Specialist', 'Purchase Manager'],
    Logistics: ['Logistics Manager', 'Warehouse Supervisor', 'Fleet Manager', 'Supply Chain Coordinator', 'Logistics Executive'],
    'R&D': ['Research Scientist', 'Research Associate', 'R&D Manager', 'Lab Technician', 'Senior Scientist', 'Innovation Lead']
  },
  Student: {
    General: ['Student', 'Scholar', 'Candidate', 'Researcher', 'Undergraduate', 'Postgraduate'],
    'Computer Science': ['CS Student', 'B.Tech Student', 'M.Tech Student', 'BCA Student', 'MCA Student', 'PhD Scholar'],
    Business: ['BBA Student', 'MBA Student', 'Management Student', 'PGDM Student'],
    Engineering: ['Engineering Student', 'B.E. Student', 'Diploma Student', 'Polytechnic Student'],
    Arts: ['Arts Student', 'B.A. Student', 'M.A. Student', 'Fine Arts Student'],
    Science: ['Science Student', 'B.Sc Student', 'M.Sc Student', 'Research Student']
  },
  Intern: {
    General: ['Intern', 'Summer Intern', 'Graduate Intern', 'Project Intern', 'Trainee'],
    IT: ['Software Intern', 'IT Support Intern', 'Web Development Intern', 'Systems Intern', 'Network Intern'],
    'Software Development': ['Software Development Intern', 'Frontend Development Intern', 'Backend Development Intern', 'Full Stack Intern', 'QA Intern'],
    'GIS & Remote Sensing': ['GIS Intern', 'Remote Sensing Intern', 'Survey Intern', 'Photogrammetry Intern'],
    'Human Resources': ['HR Intern', 'Recruiting Intern', 'HR Operations Intern', 'People Ops Intern'],
    Finance: ['Finance Intern', 'Accounting Intern', 'Audit Intern', 'Tax Intern'],
    Marketing: ['Marketing Intern', 'Digital Marketing Intern', 'Social Media Intern', 'Content Intern'],
    'Business Development': ['BD Intern', 'Sales Strategy Intern', 'Market Research Intern'],
    'Artificial Intelligence': ['AI Intern', 'Machine Learning Intern', 'Data Science Intern', 'Data Analyst Intern'],
    'Cyber Security': ['Cyber Security Intern', 'Security Analysis Intern', 'Pentesting Intern'],
    'UI/UX Design': ['UI/UX Design Intern', 'Graphic Design Intern', 'Visual Design Intern'],
    Operations: ['Operations Intern', 'Logistics Intern', 'Supply Chain Intern'],
    Administration: ['Admin Intern', 'Office Management Intern', 'Executive Assistant Intern']
  },
  Consultant: {
    General: ['Consultant', 'Senior Consultant', 'External Advisor', 'Subject Matter Expert', 'Principal Consultant', 'Managing Consultant'],
    IT: ['Senior IT Consultant', 'Solutions Architect', 'Technical Consultant', 'IT Strategy Advisor'],
    'Software Development': ['Technical Consultant', 'Architecture Consultant', 'DevOps Consultant'],
    'GIS & Remote Sensing': ['GIS Consultant', 'Geospatial Advisor', 'Remote Sensing Expert'],
    'Human Resources': ['HR Strategy Consultant', 'Change Management Expert', 'Recruitment Consultant'],
    Finance: ['Financial Advisor', 'Tax Consultant', 'Investment Consultant'],
    Marketing: ['Marketing Strategist', 'Brand Consultant', 'Digital Marketing Expert'],
    'Business Development': ['Strategy Consultant', 'Business Consultant', 'Growth Advisor'],
    'Artificial Intelligence': ['AI Consultant', 'ML Advisor', 'Data Science Consultant'],
    'Cyber Security': ['Security Consultant', 'Security Auditor', 'Compliance Consultant'],
    'UI/UX Design': ['Design Consultant', 'Experience Advisor', 'UX Strategy Consultant'],
    Operations: ['Operations Consultant', 'Management Consultant', 'Supply Chain Advisor'],
    Administration: ['Admin Consultant', 'Compliance Advisor', 'Organizational Consultant']
  },
  Trainer: {
    General: ['Trainer', 'Instructor', 'Coach', 'Mentor', 'Lead Trainer', 'Educational Consultant'],
    IT: ['Technical Trainer', 'Software Instructor', 'Network Trainer', 'IT Support Coach'],
    'Software Development': ['Coding Instructor', 'Web Development Trainer', 'Full Stack Coach'],
    'GIS & Remote Sensing': ['GIS Trainer', 'RS Instructor', 'Mapping Expert', 'Photogrammetry Trainer'],
    'Human Resources': ['Soft Skills Trainer', 'HR Trainer', 'Leadership Coach', 'Behavioral Trainer'],
    Finance: ['Financial Literacy Trainer', 'Taxation Instructor', 'Accounts Trainer'],
    Marketing: ['Digital Marketing Trainer', 'Sales Trainer', 'Marketing Coach'],
    'Business Development': ['Business Strategy Trainer', 'Pitch Coach', 'Growth Mentor'],
    'Artificial Intelligence': ['AI Trainer', 'Data Science Instructor', 'ML Coach'],
    'Cyber Security': ['Security Trainer', 'Ethical Hacking Instructor', 'Cyber Safety Coach'],
    'UI/UX Design': ['Design Instructor', 'UX Workshop Lead', 'Creative Mentor'],
    Operations: ['Operations Trainer', 'Project Management Instructor', 'Supply Chain Coach'],
    Administration: ['Compliance Trainer', 'Office Skills Instructor', 'Admin Coach']
  },
  Volunteer: {
    General: ['Volunteer', 'Event Volunteer', 'Social Worker', 'Community Helper', 'Lead Volunteer'],
    IT: ['Technical Volunteer', 'IT Support Volunteer'],
    'Software Development': ['Software Volunteer', 'Coding Volunteer'],
    'GIS & Remote Sensing': ['GIS Volunteer', 'Mapping Volunteer'],
    'Human Resources': ['HR Volunteer', 'Recruitment Volunteer'],
    Finance: ['Finance Volunteer', 'Accounts Volunteer'],
    Marketing: ['Marketing Volunteer', 'Social Media Volunteer'],
    'Business Development': ['BD Volunteer', 'Outreach Volunteer'],
    'Artificial Intelligence': ['AI Research Volunteer'],
    'Cyber Security': ['Security Volunteer'],
    'UI/UX Design': ['Design Volunteer'],
    Operations: ['Ops Volunteer', 'Logistics Volunteer'],
    Administration: ['Admin Volunteer', 'Office Volunteer']
  },
  'Research Associate': {
    General: ['Research Associate', 'Researcher', 'Junior Scientist', 'Senior Research Associate', 'Principal Researcher'],
    IT: ['IT Research Associate', 'Systems Researcher', 'Network Researcher'],
    'Software Development': ['Software Research Engineer', 'Dev Researcher', 'Algorithmic Researcher'],
    'GIS & Remote Sensing': ['Geospatial Researcher', 'Remote Sensing Associate', 'Satellite Imagery Analyst'],
    'Human Resources': ['HR Research Associate', 'People Analytics Researcher'],
    Finance: ['Financial Researcher', 'Economic Analyst'],
    Marketing: ['Market Research Analyst', 'Consumer Behavior Researcher'],
    'Business Development': ['Strategic Research Associate', 'Industry Analyst'],
    'Artificial Intelligence': ['Senior Research Associate', 'AI Researcher', 'Machine Learning Researcher'],
    'Cyber Security': ['Cyber Research Analyst', 'Threat Intelligence Researcher'],
    'UI/UX Design': ['UX Researcher', 'Design Researcher', 'Human Factors Engineer'],
    Operations: ['Operations Researcher', 'Process Optimization Analyst'],
    Administration: ['Admin Research Associate', 'Organizational Researcher']
  },
  'Project Associate': {
    General: ['Project Associate', 'Project Assistant', 'Senior Project Associate', 'Lead Project Associate'],
    IT: ['IT Project Associate', 'Systems Project Coordinator'],
    'Software Development': ['Project Associate', 'Technical Coordinator', 'Dev Project Associate'],
    'GIS & Remote Sensing': ['GIS Project Associate', 'Geospatial Coordinator'],
    'Human Resources': ['HR Project Associate', 'People Project Lead'],
    Finance: ['Finance Project Associate', 'Budget Coordinator'],
    Marketing: ['Marketing Project Associate', 'Campaign Coordinator'],
    'Business Development': ['BD Project Associate', 'Growth Project Lead'],
    'Artificial Intelligence': ['AI Project Associate', 'Data Project Coordinator'],
    'Cyber Security': ['Security Project Associate', 'Compliance Project Lead'],
    'UI/UX Design': ['Design Project Associate', 'UX Project Coordinator'],
    Operations: ['Project Associate', 'Project Coordinator', 'Ops Project Associate'],
    Administration: ['Admin Project Associate', 'Office Project Lead']
  },
  HR: {
    General: ['HR Specialist', 'HR Support', 'HR Assistant', 'People Associate'],
    'Human Resources': ['HR Lead', 'HR Partner', 'HR Advisor', 'Recruitment Specialist', 'Employee Success Partner']
  },
  Management: {
    General: ['Management Staff', 'Office Manager', 'Executive Assistant', 'Manager', 'Managing Director'],
    Operations: ['Operations Manager', 'Project Manager', 'Team Lead', 'Operations Director'],
    Administration: ['Admin Manager', 'Management Partner', 'Administrative Director'],
    'Business Development': ['BD Manager', 'Strategic Partner', 'Growth Director']
  },
  Guest: {
    General: ['Guest', 'Personal Visit', 'Subject Matter Expert', 'Special Guest', 'VIP Guest'],
    'Client Visit': ['Client Representative', 'Potential Partner', 'Existing Client'],
    Meeting: ['Meeting Participant', 'Vendor Representative', 'External Consultant']
  },
  Vendor: {
    General: ['Vendor', 'Service Provider', 'External Partner', 'Supplier', 'Contractor'],
    'IT Services': ['System Consultant', 'Network Technician', 'Software Vendor', 'Hardware Supplier'],
    'Facility Management': ['Facility Supervisor', 'Maintenance Staff', 'Facility Manager'],
    Catering: ['Catering Manager', 'Head Chef', 'Service Staff', 'Pantry Manager'],
    Security: ['Security Head', 'Security Guard', 'CCTV Operator', 'Security Agency Lead'],
    Transport: ['Fleet Supervisor', 'Driver', 'Transport Coordinator', 'Travel Agent'],
    Maintenance: ['Electrician', 'Plumber', 'HVAC Technician', 'Technician', 'Handyman'],
    'Supply Chain': ['Supplier Representative', 'Logistics Agent', 'Wholesale Partner'],
    'Printing & Stationery': ['Printing In-charge', 'Delivery Agent', 'Stationery Vendor'],
    'Cleaning Services': ['Cleaning Supervisor', 'Housekeeping Staff', 'Janitorial Lead'],
    Electrical: ['Electrical Contractor', 'Senior Electrician', 'UPS Technician']
  },
  Visitor: {
    General: ['Visitor', 'Personal Visitor', 'Relative', 'Friend'],
    'Client Visit': ['Prospective Client', 'Existing Client', 'Corporate Visitor'],
    Government: ['Govt Official', 'Tax Officer', 'Regulator', 'Inspector'],
    Audit: ['Internal Auditor', 'External Auditor', 'ISO Auditor', 'Compliance Officer'],
    Interview: ['Candidate', 'Applicant', 'Potential Employee'],
    Meeting: ['Meeting Participant', 'External Partner', 'Board Member'],
    Event: ['Event Attendee', 'Participant', 'Guest Speaker'],
    Delivery: ['Courier', 'Delivery Partner', 'Supply Delivery', 'Postman']
  },
  Contractor: {
    General: ['Contractor', 'Sub-Contractor', 'Supervisor', 'Project Contractor'],
    IT: ['IT Contractor', 'Software Consultant', 'Network Contractor'],
    Civil: ['Civil Contractor', 'Site Supervisor', 'Mason', 'Civil Engineer'],
    Electrical: ['Electrical Contractor', 'Wireman', 'Electrician', 'Electrical Supervisor'],
    Mechanical: ['Mechanical Contractor', 'Fitter', 'Mechanical Technician'],
    Construction: ['Site In-charge', 'Contractor', 'Construction Lead'],
    Plumbing: ['Plumbing Contractor', 'Plumber', 'Pipe Fitter'],
    HVAC: ['AC Technician', 'HVAC Specialist', 'Cooling Expert'],
    'Interior Design': ['Interior Designer', 'Decorator', 'Furniture Designer'],
    Landscaping: ['Landscape Artist', 'Gardening Lead', 'Horticulturist'],
    'Security Systems': ['CCTV Technician', 'Security Consultant', 'Biometric Expert']
  },
  Others: {
    General: ['Temporary Staff', 'Freelancer', 'Partner', 'Board Member', 'Advisor', 'Volunteer', 'Affiliate', 'Specialist'],
    'Temporary Staff': ['Temp Staff', 'Contract Helper', 'Daily Wager'],
    Freelancer: ['Freelance Developer', 'Freelance Designer', 'Content Writer', 'Freelance Consultant'],
    Partner: ['Strategic Partner', 'Business Partner', 'Channel Partner'],
    'Board Member': ['Director', 'Board Representative', 'Executive Member'],
    Advisor: ['Consultant', 'Advisor', 'Mentor', 'Expert Advisor'],
    Volunteer: ['Volunteer Helper', 'Community Volunteer']
  }
};

export const THEME_COLORS = [
  { id: 'classic', name: 'Classical Gold', primary: '#bb9539', bg: '#fffdf5', accent: '#8c6d1f' },
  { id: 'modern', name: 'Modern Tech', primary: '#1e5cdc', bg: '#f0f7ff', accent: '#1648b0' },
  { id: 'minimal', name: 'Minimalist Sleek', primary: '#18181b', bg: '#fafafa', accent: '#3f3f46' },
  { id: 'emerald', name: 'Emerald Success', primary: '#059669', bg: '#f0fdf4', accent: '#047857' },
  { id: 'navy', name: 'Deep Ocean', primary: '#1e3a8a', bg: '#f8fafc', accent: '#1d4ed8' },
  { id: 'sunset', name: 'Sunset Horizon', primary: '#f97316', bg: '#fff7ed', accent: '#c2410c' },
  { id: 'lavender', name: 'Lavender Mist', primary: '#8b5cf6', bg: '#f5f3ff', accent: '#6d28d9' },
  { id: 'forest', name: 'Forest Peak', primary: '#15803d', bg: '#f0fdf4', accent: '#166534' },
  { id: 'slate', name: 'Midnight Slate', primary: '#334155', bg: '#f8fafc', accent: '#1e293b' },
  { id: 'rose', name: 'Rose Quartz', primary: '#db2777', bg: '#fdf2f8', accent: '#be185d' },
  { id: 'royal', name: 'Royal Purple', primary: '#7c3aed', bg: '#f5f3ff', accent: '#5b21b6' },
  { id: 'crimson', name: 'Crimson Elite', primary: '#dc2626', bg: '#fef2f2', accent: '#991b1b' },
  { id: 'charcoal', name: 'Charcoal Grey', primary: '#4b5563', bg: '#f9fafb', accent: '#1f2937' },
  { id: 'earth', name: 'Earth Tone', primary: '#92400e', bg: '#fffbeb', accent: '#78350f' },
  // Additional Premium Themes
  { id: 'obsidian', name: 'Obsidian Night', primary: '#0f172a', bg: '#f1f5f9', accent: '#334155' },
  { id: 'cyber', name: 'Cyber Neon', primary: '#7000ff', bg: '#fafafa', accent: '#bc00ff' },
  { id: 'platinum', name: 'Platinum Silver', primary: '#64748b', bg: '#f8fafc', accent: '#94a3b8' },
  { id: 'autumn', name: 'Autumn Rust', primary: '#c2410c', bg: '#fffaf0', accent: '#7c2d12' },
];
