export const COUNTRIES = [
  { name: "India", code: "+91", iso: "IN", flag: "🇮🇳" },
  { name: "United States", code: "+1", iso: "US", flag: "🇺🇸" },
  { name: "United Kingdom", code: "+44", iso: "GB", flag: "🇬🇧" },
  { name: "Australia", code: "+61", iso: "AU", flag: "🇦🇺" },
  { name: "Canada", code: "+1", iso: "CA", flag: "🇨🇦" },
  { name: "UAE", code: "+971", iso: "AE", flag: "🇦🇪" },
  { name: "Saudi Arabia", code: "+966", iso: "SA", flag: "🇸🇦" },
  { name: "Singapore", code: "+65", iso: "SG", flag: "🇸🇬" },
  { name: "New Zealand", code: "+64", iso: "NZ", flag: "🇳🇿" },
  { name: "South Africa", code: "+27", iso: "ZA", flag: "🇿🇦" },
  { name: "Afghanistan", code: "+93", iso: "AF", flag: "🇦🇫" },
  { name: "Bangladesh", code: "+880", iso: "BD", flag: "🇧🇩" },
  { name: "Bhutan", code: "+975", iso: "BT", flag: "🇧🇹" },
  { name: "China", code: "+86", iso: "CN", flag: "🇨🇳" },
  { name: "Indonesia", code: "+62", iso: "ID", flag: "🇮🇩" },
  { name: "Iran", code: "+98", iso: "IR", flag: "🇮🇷" },
  { name: "Iraq", code: "+964", iso: "IQ", flag: "🇮🇶" },
  { name: "Israel", code: "+972", iso: "IL", flag: "🇮🇱" },
  { name: "Japan", code: "+81", iso: "JP", flag: "🇯🇵" },
  { name: "Jordan", code: "+962", iso: "JO", flag: "🇯🇴" },
  { name: "Kuwait", code: "+965", iso: "KW", flag: "🇰🇼" },
  { name: "Malaysia", code: "+60", iso: "MY", flag: "🇲🇾" },
  { name: "Maldives", code: "+960", iso: "MV", flag: "🇲🇻" },
  { name: "Nepal", code: "+977", iso: "NP", flag: "🇳🇵" },
  { name: "Oman", code: "+968", iso: "OM", flag: "🇴🇲" },
  { name: "Pakistan", code: "+92", iso: "PK", flag: "🇵🇰" },
  { name: "Philippines", code: "+63", iso: "PH", flag: "🇵🇭" },
  { name: "Qatar", code: "+974", iso: "QA", flag: "🇶🇦" },
  { name: "South Korea", code: "+82", iso: "KR", flag: "🇰🇷" },
  { name: "Sri Lanka", code: "+94", iso: "LK", flag: "🇱🇰" },
  { name: "Thailand", code: "+66", iso: "TH", flag: "🇹🇭" },
  { name: "Turkey", code: "+90", iso: "TR", flag: "🇹🇷" },
  { name: "Vietnam", code: "+84", iso: "VN", flag: "🇻🇳" },
  { name: "Albania", code: "+355", iso: "AL", flag: "🇦🇱" },
  { name: "Austria", code: "+43", iso: "AT", flag: "🇦🇹" },
  { name: "Belgium", code: "+32", iso: "BE", flag: "🇧🇪" },
  { name: "Bulgaria", code: "+359", iso: "BG", flag: "🇧🇬" },
  { name: "Croatia", code: "+385", iso: "HR", flag: "🇭🇷" },
  { name: "Cyprus", code: "+357", iso: "CY", flag: "🇨🇾" },
  { name: "Czech Republic", code: "+420", iso: "CZ", flag: "🇨🇿" },
  { name: "Denmark", code: "+45", iso: "DK", flag: "🇩🇰" },
  { name: "Finland", code: "+358", iso: "FI", flag: "🇫🇮" },
  { name: "France", code: "+33", iso: "FR", flag: "🇫🇷" },
  { name: "Germany", code: "+49", iso: "DE", flag: "🇩🇪" },
  { name: "Greece", code: "+30", iso: "GR", flag: "🇬🇷" },
  { name: "Hungary", code: "+36", iso: "HU", flag: "🇭🇺" },
  { name: "Iceland", code: "+354", iso: "IS", flag: "🇮🇸" },
  { name: "Ireland", code: "+353", iso: "IE", flag: "🇮🇪" },
  { name: "Italy", code: "+39", iso: "IT", flag: "🇮🇹" },
  { name: "Netherlands", code: "+31", iso: "NL", flag: "🇳🇱" },
  { name: "Norway", code: "+47", iso: "NO", flag: "🇳🇴" },
  { name: "Poland", code: "+48", iso: "PL", flag: "🇵🇱" },
  { name: "Portugal", code: "+351", iso: "PT", flag: "🇵🇹" },
  { name: "Romania", code: "+40", iso: "RO", flag: "🇷🇴" },
  { name: "Russia", code: "+7", iso: "RU", flag: "🇷🇺" },
  { name: "Spain", code: "+34", iso: "ES", flag: "🇪🇸" },
  { name: "Sweden", code: "+46", iso: "SE", flag: "🇸🇪" },
  { name: "Switzerland", code: "+41", iso: "CH", flag: "🇨🇭" },
  { name: "Ukraine", code: "+380", iso: "UA", flag: "🇺🇦" },
  { name: "Algeria", code: "+213", iso: "DZ", flag: "🇩🇿" },
  { name: "Egypt", code: "+20", iso: "EG", flag: "🇪🇬" },
  { name: "Ethiopia", code: "+251", iso: "ET", flag: "🇪🇹" },
  { name: "Ghana", code: "+233", iso: "GH", flag: "🇬🇭" },
  { name: "Kenya", code: "+254", iso: "KE", flag: "🇰🇪" },
  { name: "Morocco", code: "+212", iso: "MA", flag: "🇲🇦" },
  { name: "Nigeria", code: "+234", iso: "NG", flag: "🇳🇬" },
  { name: "Tanzania", code: "+255", iso: "TZ", flag: "🇹🇿" },
  { name: "Uganda", code: "+256", iso: "UG", flag: "🇺🇬" },
  { name: "Argentina", code: "+54", iso: "AR", flag: "🇦🇷" },
  { name: "Brazil", code: "+55", iso: "BR", flag: "🇧🇷" },
  { name: "Chile", code: "+56", iso: "CL", flag: "🇨🇱" },
  { name: "Colombia", code: "+57", iso: "CO", flag: "🇨🇴" },
  { name: "Mexico", code: "+52", iso: "MX", flag: "🇲🇽" },
  { name: "Peru", code: "+51", iso: "PE", flag: "🇵🇪" },
  { name: "Venezuela", code: "+58", iso: "VE", flag: "🇻🇪" },
  { name: "Fiji", code: "+679", iso: "FJ", flag: "🇫🇯" },
  { name: "Papua New Guinea", code: "+675", iso: "PG", flag: "🇵🇬" },
];
